version: 2.1
jobs:
  lint-lookML:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: checkout LAMS (LookML linting) repo and install
          command: cd ..; git clone https://github.com/looker-open-source/look-at-me-sideways.git; cd look-at-me-sideways; npm install
      - run:
          name: execute linting
          command: cd ..; cd renew-looker-template; node ../look-at-me-sideways