version: 2.1
jobs:
  lint-lookML:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Checkout LAMS (LookML linting) repo and install
          command: cd ..; git clone https://github.com/looker-open-source/look-at-me-sideways.git; cd look-at-me-sideways; npm install
      - run:
          name: Execute linting
          command: cd ..; cd project; if node ../look-at-me-sideways --reporting=no; then "No linting errors."; else echo "Liniting errors found"; cat issues.md; fi 
workflows:
  version: 2
  main-linting:
    jobs:
      - lint-lookML