version: 2.1
jobs:
  lint-lookML:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Execute linting
          command: |
            npm set prefix ~/.npm
            PATH="$HOME/.npm/bin:$PATH"
            PATH="./node_modules/.bin:$PATH"
            source ~/.bashrc
            npm install -g @looker/look-at-me-sideways;
            if lams --reporting=no;
            then echo "No linting errors found.";
            else echo "Linting errors found.";
            touch FAIL
            fi;
      - run:
          name: Send comment to Github
          command: |
            echo "Install python3"
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python3 get-pip.py
            sudo pip3 install PyGithub
            PR_NUM=${CIRCLE_PULL_REQUEST##*/}
            echo "Execute comment submission"
            echo "GITHUB_REPO_OWNER: $GITHUB_REPO_OWNER"
            echo "GITHUB_REPO_NAME: $GITHUB_REPO_NAME"
            echo "PR_NUM: $PR_NUM"
            echo "PWD: $(pwd)"
            python3 .circleci/scripts/push_comment_gh.py $GITHUB_USER_TOKEN $GITHUB_REPO_OWNER $GITHUB_REPO_NAME $PR_NUM $(pwd)
      - run:
          name: Indicate fail or success
          command: |
            if test -f FAIL;
            then echo "Failure. Linting errors found. See PR on github.";
            exit 1;
            else echo "No errors found.";
            exit 0;
            fi
workflows:
  version: 2
  main-linting:
    jobs:
      - lint-lookML:
          filters:
            branches:
              ignore:
                - master
