version: 2.1
jobs:
  lint-lookML:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Checkout LAMS (LookML linting) repo and install
          command: cd ..; git clone https://github.com/looker-open-source/look-at-me-sideways.git; cd look-at-me-sideways; npm install
      - run:
          name: Execute linting
          command: cd ..; cd project; node ../look-at-me-sideways --reporting=no
workflows:
  version: 2
  main-linting:
    jobs:
      - lint-lookML